version: '3'
services:
  minio:
    image: quay.io/minio/minio
    restart: always
    container_name: file_storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    networks:
      abrbar_prod_base_network:
        ipv4_address: 172.16.50.90

networks:
  abrbar_prod_base_network:
    external: true