version: "3"

services:
  minio:
    image: minio/minio
    container_name: file_storage
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./data:/data
      - ./config:/root/.minio
    command: server /data
    networks:
      abrbar_prod_base_network:
        ipv4_address: 172.16.50.90
  

networks:
  abrbar_prod_base_network:
    external: true
